import ThemeColors from '../assets/theme/ThemeColors';

export const ClubsfilterList = [
  {
    id: 0,
    title: 'All',
    foregroundCol: ThemeColors.White,
    backgroundCol: ThemeColors.GoogleGreen,
    borderRad: 20,
    paddingHor: 20,
    buttonHeight: 'auto',
    textSize: 16,
    textWeight: '500',
  },
  {
    id: 1,
    title: 'Arts and Science',
    foregroundCol: ThemeColors.White,
    backgroundCol: ThemeColors.GoogleRed,
    borderRad: 20,
    paddingHor: 20,
    buttonHeight: 'auto',
    textSize: 16,
    textWeight: '500',
  },
  {
    id: 2,
    title: 'Education',
    foregroundCol: ThemeColors.White,
    backgroundCol: ThemeColors.GoogleYellow,
    borderRad: 20,
    paddingHor: 20,
    buttonHeight: 'auto',
    textSize: 16,
    textWeight: '500',
  },
  {
    id: 3,
    title: 'Engineering',
    foregroundCol: ThemeColors.White,
    backgroundCol: ThemeColors.GoogleBlue,
    borderRad: 20,
    paddingHor: 20,
    buttonHeight: 'auto',
    textSize: 16,
    textWeight: '500',
  },
  {
    id: 4,
    title: 'Pharmacy',
    foregroundCol: ThemeColors.White,
    backgroundCol: ThemeColors.Purple_Veronica,
    borderRad: 20,
    paddingHor: 20,
    buttonHeight: 'auto',
    textSize: 16,
    textWeight: '500',
  },
];
