import ThemeColors from '../assets/theme/ThemeColors';
export const SharingCenterFilterList = [
  {
    id: 0,
    title: 'All',
    foregroundCol: ThemeColors.White,
    backgroundCol: ThemeColors.GoogleGreen,
    borderRad: 20,
    paddingHor: 20,
    buttonHeight: 'auto',
    textSize: 16,
    textWeight: '500',
  },
  {
    id: 1,
    title: 'Art',
    foregroundCol: ThemeColors.White,
    backgroundCol: ThemeColors.GoogleRed,
    borderRad: 20,
    paddingHor: 20,
    buttonHeight: 'auto',
    textSize: 16,
    textWeight: '500',
  },
  {
    id: 2,
    title: 'Book',
    foregroundCol: ThemeColors.White,
    backgroundCol: ThemeColors.GoogleYellow,
    borderRad: 20,
    paddingHor: 20,
    buttonHeight: 'auto',
    textSize: 16,
    textWeight: '500',
  },
  {
    id: 3,
    title: 'Electronics',
    foregroundCol: ThemeColors.White,
    backgroundCol: ThemeColors.GoogleBlue,
    borderRad: 15,
    paddingHor: 20,
    buttonHeight: 'auto',
    textSize: 16,
    textWeight: '500',
  },
  {
    id: 4,
    title: 'Science',
    foregroundCol: ThemeColors.White,
    backgroundCol: ThemeColors.Purple_Veronica,
    borderRad: 20,
    paddingHor: 20,
    buttonHeight: 'auto',
    textSize: 16,
    textWeight: '500',
  },
];
